core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dotpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.task, name='task'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:pk>/completed/', views.completed, name='completed'),
]

task/models.py
from django.db import models
from account.models import User
from project.models import Project
from todolist.models import Todolist
import uuid
# Create your models here.
class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')
    todolist = models.ForeignKey(Todolist, on_delete=models.CASCADE, related_name="tasks")
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.name

task/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from project.models import Project
from todolist.models import Todolist
from .models import Task
# Create your views here.
@login_required(login_url="/login/")
def add(request, project_id, todolist_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id) 

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        
        Task.objects.create(project=project, todolist=todolist, name=name, description=description, created_by=request.user)
        return redirect(f'/projects/{project_id}/{todolist_id}/')
    return render(request, 'task/add.html')

@login_required(login_url="/login/")
def task(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id) 
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    
    # if request.GET.get('is_done', '') == 'yes':
    #     task.is_done = True
    #     task.save()

    return render(request, 'task/task.html', {'task': task})

@login_required(login_url="/login/")
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id) 
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        
        if name:
            task.name = name
        task.description = description
        task.save()
        return redirect(f'/projects/{project_id}/{todolist_id}/')
    
    return render(request, 'task/edit.html', {'task': task})

@login_required(login_url="/login/")
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id) 
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    
    task.delete()

    return redirect(f'/projects/{project_id}/{todolist_id}/')

@login_required(login_url="/login/")
def completed(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id) 
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    task.is_done = True
    task.save()

    return redirect(f'/projects/{project_id}/{todolist_id}/')

task/templates/task/add.html
{% extends "core/base.html" %}

{% block content %}
<div class="p-4">
<h1 class="text-3xl mb-6 font-semibold">Add Task</h1>
<form action="." class="mt-6 space-y-4" method="post">
    {% csrf_token %}
    <div>
        <label>Name</label> <br/>
        <input type="name" name="name" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
    </div>
    <div>
        <label>Description</label> <br/>
        <input type="text" name="description" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
    </div>
   
    <div>
        <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Create</button>
    </div>
</form>
</div>
{% endblock content %}

task/templates/task/edit.html
{% extends 'core/base.html' %}

{% block content %}
<div class="p-4">
    <h1 class="mb-6 text-3xl font-semibold">Edit Task</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ task.name }}" type="text" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">{{ task.description }}</textarea>
        </div>

        <div>
            <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Update</button>
        </div>
    </form>
</div>
{% endblock %}

task/templates/task/task.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="p-4 border rounded-xl">
        <h1 class="mb-6 text-3xl">{{ task.name }}</h1>

        <p><strong class="font-bold">Status: </strong>{% if task.is_done %} Completed {% else %} In Progress {% endif %} </p>
        {% if task.description %}
            <p class="mb-6 mt-2">{{ task.description }}</p>
        {% endif %}
        {% if not task.is_done %}
        <a href="{% url 'task:completed' task.project_id task.todolist_id task.id%}" class="py-4 px-8 bg-emerald-600 text-white inline-block rounded-full hover:opacity-80 transition">Mark Complete</a>
        {% endif %}
        <a href="{% url 'task:edit' task.project_id task.todolist_id task.id%}" class="py-4 px-8 bg-sky-600 text-white inline-block rounded-full hover:opacity-80 transition">Edit</a>
        <a href="{% url 'task:delete' task.project_id task.todolist_id task.id%}" class="py-4 px-8 bg-red-600 text-white inline-block rounded-full hover:opacity-80 transition">Delete</a>

    </div>    
{% endblock %}