core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dotpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.task, name='task'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:pk>/completed/', views.completed, name='completed'),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

todolist/models.py
from django.db import models
from account.models import User
from project.models import Project
import uuid
# Create your models here.
class Todolist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='todolists')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='todolists')

    def __str__(self):
        return self.name

todolist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Project
from .models import Todolist
# Create your views here.
@login_required(login_url="/login/")
def add(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    if request.method == 'POST':
        name = request.POST.get('name' '')
        description = request.POST.get('description' '')

        if name:
            Todolist.objects.create(name=name, description=description, project=project, created_by=request.user)
            return redirect(f'/projects/{project_id}/')
    return render(request, 'todolist/add.html', {'project': project})

@login_required(login_url="/login/")
def todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)
    tasks_ = todolist.tasks.all()
    completed_task = tasks_.filter(is_done=True)

    return render(request, 'todolist/todolist.html', {'project': project, 'todolist': todolist, 'completed_task': completed_task})

@login_required(login_url="/login/")
def edit(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name' '')
        description = request.POST.get('description' '')
       
        if name:
            todolist.name = name
            todolist.description = description
            todolist.save()
            print(todolist)
            return redirect(f'/projects/{project_id}/{pk}/')
           
    return render(request, 'todolist/edit.html', {'project': project, 'todolist': todolist})

@login_required(login_url="/login/")
def delete(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    todolist.delete()

    return redirect(f'/projects/{project_id}/')

todolist/templates/todolist/add.html
{% extends "core/base.html" %}

{% block content %}
<div class="p-4">
    <h1 class="text-2xl mb-6 font-semibold">Add To-do List</h1>
    <hr>
    <form action="." class="mt-6 space-y-6" method="post">
        {% csrf_token %}
        <div class="">
            <label class="font-medium text-base">Name: </label> <br/>
            <input type="text" name="name" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>
        <div class="">
            <label class="font-medium text-base">Description: </label> <br/>
            <input type="text" name="description" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>
        <div>
            <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Create</button>
        </div>
    </form>
</div>
{% endblock content %}

todolist/templates/todolist/edit.html
{% extends 'core/base.html' %}

{% block content %}
<div class="p-4">
    <h1 class="mb-6 text-3xl font-semibold">Edit To-do List</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ todolist.name }}" type="text" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none" rows=10>{{ todolist.description }}</textarea>
        </div>

        <div>
            <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Update</button>
        </div>
    </form>
</div>
{% endblock %}

todolist/templates/todolist/todolist.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="p-4">
        <h1 class="mb-6 text-3xl font-bold">{{ todolist.name }}</h1>

        {% if todolist.description %}
            <p class="mb-6">{{ todolist.description }}</p>
        {% endif %}

        <p class="mb-4 mt-2 font-bold text-xl">{{completed_task.all|length}} / {{todolist.tasks.all|length}}</p>
        <a href="{% url 'task:add' project.id todolist.id%}" class="py-4 px-8 bg-emerald-600 text-white inline-block rounded-full hover:opacity-80 transition">Add task</a>
        <a href="{% url 'todolist:edit' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block rounded-full hover:opacity-80 transition">Edit</a>
        <a href="{% url 'todolist:delete' project.id todolist.id%}" class="py-4 px-8 bg-red-600 text-white inline-block rounded-full hover:opacity-80 transition">Delete</a>

        <hr class="mt-4">

        <div class="mt-6 grid grid-cols-4 gap-4">
            {% for task in todolist.tasks.all %}
                <div class="py-6 px-6 shadow-lg {% if task.is_done %} bg-emerald-600 text-white {% else %} bg-amber-200 text-black {% endif %} rounded-xl hover:opacity-80 transition">
                    <a href="{% url 'task:task' todolist.project.id todolist.id task.id %}">
                        <div class="flex flex-col justify-around gap-2 h-full">
                            <h2 class="text-xl">{{ task.name }}</h2>

                            <p class="text-sm">
                                {{ task.description }}
                            </p>
                            <p class="">
                                <strong class="font-bold">Status: </strong>
                                {% if task.is_done %} Completed {% else %} In Progress {% endif %} 
                            </p>
                        </div>

                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}