core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dotpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add_project, name='add_project'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit_project'),
    path('<uuid:pk>/delete/', views.delete_project, name='delete_project'),
    path('<uuid:project_id>/files/upload/',
         views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/',
         views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note, name='note'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/',
         views.edit_note, name='edit_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/',
         views.delete_note, name='delete_note'),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

project/models.py
from django.db import models
from django.dispatch import receiver
from account.models import User
import uuid

# Create your models here.


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='projects')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ProjectFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='files')
    name = models.CharField(max_length=255)
    attachment = models.FileField(upload_to='projectfiles',)

    def __str__(self):
        return self.name


@receiver(models.signals.post_delete, sender=ProjectFile)
def remove_file_from_s3(sender, instance, using, **kwargs):
    instance.attachment.delete(save=False)


class ProjectNote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='notes')
    name = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

project/forms.py
from django.forms import ModelForm
from .models import ProjectFile
from django import forms

class ProjectFileForm(ModelForm):
    class Meta:
        model = ProjectFile
        fields = ['name', 'attachment']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none'}),
            'attachment': forms.FileInput(attrs={'class': 'w-full py-6 px-6',}),
        }
        

project/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import ProjectFileForm
from .models import Project, ProjectNote


@login_required(login_url='/login/')
def projects(request):
    projects = Project.objects.filter(created_by=request.user)

    return render(request, 'project/projects.html', {
        'projects': projects
    })


@login_required(login_url="/login/")
def project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'project/project.html', {
        'project': project
    })


@login_required(login_url="/login/")
def add_project(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Project.objects.create(
                name=name, description=description, created_by=request.user)

            return redirect('/projects/')
        else:
            print('Not valid')

    return render(request, 'project/add_project.html')


@login_required(login_url="/login/")
def edit_project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            project.name = name
            project.description = description
            project.save()

            return redirect('/projects/')

    return render(request, 'project/edit_project.html', {
        'project': project
    })


@login_required(login_url="/login/")
def delete_project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)
    project.delete()

    return redirect('/projects/')


# Files


@login_required(login_url="/login/")
def upload_file(request, project_id):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        form = ProjectFileForm(request.POST, request.FILES)

        if form.is_valid():
            projectfile = form.save(commit=False)
            projectfile.project = project
            projectfile.save()

            return redirect(f'/projects/{project_id}/')
    else:
        form = ProjectFileForm()

    return render(request, 'project/upload_file.html', {
        'project': project,
        'form': form
    })


@login_required(login_url="/login/")
def delete_file(request, project_id, pk):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)
    projectfile = project.files.get(pk=pk)
    projectfile.delete()

    return redirect(f'/projects/{project_id}/')


# Notes


@login_required(login_url="/login/")
def add_note(request, project_id):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            ProjectNote.objects.create(
                project=project,
                name=name,
                body=body
            )

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/add_note.html', {
        'project': project
    })


@login_required(login_url="/login/")
def note(request, project_id, pk):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    return render(request, 'project/note.html', {
        'project': project,
        'note': note
    })


@login_required(login_url="/login/")
def edit_note(request, project_id, pk):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            note.name = name
            note.body = body
            note.save()

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/edit_note.html', {
        'project': project,
        'note': note
    })


@login_required(login_url="/login/")
def delete_note(request, project_id, pk):
    project = Project.objects.filter(
        created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)
    note.delete()

    return redirect(f'/projects/{project_id}/')

project/templates/project/add_note.html
{% extends "core/base.html" %}

{% block content %}
    <h1 class="text-3xl mb-6 font-semibold">Add Note</h1>
    <hr>
    <form action="." class="mt-6 space-y-4" method="post">
        {% csrf_token %}
        <div>
            <label class="font-medium text-base">Name</label> <br/>
            <input type="name" name="name" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>
        <div>
            <label class="font-medium text-base">Body</label> <br/>
            <textarea type="text" name="body" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none" rows='10'></textarea>
        </div>
    
        <div>
            <button class="py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Add</button>
        </div>
    </form>
{% endblock content %}

project/templates/project/add_project.html
{% extends "core/base.html" %}

{% block content %}
<div class="p-4">
    <h1 class="text-2xl mb-6 font-semibold">Add Project</h1>
    <hr>
    <form action="." class="mt-6 space-y-6" method="post">
        {% csrf_token %}
        <div class="">
            <label class="font-medium text-base">Name: </label> <br/>
            <input type="text" name="name" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>
        <div class="">
            <label class="font-medium text-base">Description: </label> <br/>
            <input type="text" name="description" id="" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>
    
        <div>
            <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Create</button>
        </div>
    </form>
</div>
{% endblock content %}

project/templates/project/edit_note.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="p-4">
        <h1 class="mb-6 text-3xl font-semibold">Edit note</h1>

        <form class="mt-6 space-y-4" method="post" action=".">
            {% csrf_token %}

            <div>
                <label>Name</label><br>
                <input value="{{ note.name }}" name="name" type="text" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
            </div>

            <div>
                <label>Body</label><br>
                <textarea name="body" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none" rows="10">{{ note.body }}</textarea>
            </div>

            <div>
                <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

project/templates/project/edit_project.html
{% extends 'core/base.html' %}

{% block content %}
<div class="p-4">
    <h1 class="mb-6 text-3xl font-semibold">Edit Project</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ project.name }}" type="text" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-6 px-6 bg-slate-400 rounded-lg text-white outline-none">{{ project.description }}</textarea>
        </div>

        <div>
            <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Update</button>
        </div>
    </form>
</div>
{% endblock %}

project/templates/project/note.html
{% extends 'core/base.html' %} {% block content %}
<div class="p-4 border rounded-xl">
  <h1 class="mb-6 text-3xl">{{ note.name }}</h1>

  <a
    href="{% url 'project:edit_note' project.id note.id %}"
    class="py-4 px-8 bg-sky-600 text-white inline-block rounded-full font-bold hover:opacity-80 transition"
    >Edit</a
  >
  <a
    href="{% url 'project:delete_note' project.id note.id %}"
    class="py-4 px-8 bg-red-600 text-white inline-block rounded-full font-bold hover:opacity-80 transition"
    >Delete</a
  >

  <p class="mb-6 mt-6">{{ note.body }}</p>
</div>
{% endblock %}

project/templates/project/project.html
{% extends "core/base.html" %} {% block content %}
<div class="p-4">
  <h1 class="text-3xl mb-6 font-bold">{{project.name}}</h1>
  <hr class="mb-4" />
  {% if project.description %}
  <p class="mb-6">
    <span class="font-medium text-lg">Description:</span> <br />
    {{ project.description }}
  </p>
  <p class="mb-6">
    <span class="font-medium text-lg">Created at:</span> <br />
    {{ project.created_at }}
  </p>
  {% endif %}
  <hr />
  <a
    href="{% url 'todolist:add' project.id%}"
    class="mt-4 py-4 px-8 bg-sky-600 text-white inline-block rounded-full hover:opacity-80 transition"
    >Create To-do List</a
  >
  <a
    href="{% url 'project:edit_project' project.id%}"
    class="py-4 px-8 bg-emerald-600 text-white inline-block rounded-full hover:opacity-80 transition"
    >Edit</a
  >
  <a
    href="{% url 'project:delete_project' project.id%}"
    class="py-4 px-8 bg-red-600 text-white inline-block rounded-full hover:opacity-80 transition"
    >Delete</a
  >
  <h2 class="mt-6 mb-4 text-2xl font-semibold">To-do Lists:</h2>
  <hr />
  <div class="mt-6 grid grid-cols-4 gap-4">
    {% for todolist in project.todolists.all %}
    <div
      class="p-8 bg-neutral-200 rounded-xl flex flex-col justify-between gap-2 shadow-lg"
    >
      <h3 class="text-xl font-medium">{{todolist.name}}</h3>
      <p class="mt-2 text-sm text-neutral-500">{{todolist.description}}</p>
      <p class="mt-2 text-lg text-neutral-500 font-medium">
        Tasks: {{ todolist.tasks.all|length }}
      </p>

      <div class="flex gap-4 content-end justify-end w-full">
        <a
          href="{% url 'todolist:todolist' project.id todolist.id%}"
          class="py-2 px-6 hover:opacity-80 transition bg-emerald-600 text-white rounded-full"
          >View</a
        >
        <a
          href="{% url 'todolist:delete' project.id todolist.id%}"
          class="py-2 px-6 hover:opacity-80 transition bg-red-600 text-white rounded-full"
          >Delete</a
        >
      </div>
    </div>
    {% endfor %}
  </div>
  {% if not project.todolists.all %}
  <p class="text-neutral-600 text-lg italic text-center">
    There is no to-do list.
  </p>
  {% endif %}
  <h2 class="mt-6 mb-4 text-2xl font-semibold">Files:</h2>
  <hr />

  <div class="mt-6 grid grid-cols-4 gap-4">
    {% for projectfile in project.files.all %}
    <div class="py-6 px-6 bg-neutral-200 mb-6 rounded-xl shadow-sm">
      <h3 class="text-xl font-medium">{{projectfile.name}}</h3>
      <a
        href="{{ projectfile.attachment.url }}"
        class="text-base text-slate-600"
      >
        View File
      </a>
      |
      <a
        href="{% url 'project:delete_file' project.id projectfile.id%}"
        class="text-base text-slate-600"
      >
        Delete File
      </a>
    </div>
    {% endfor %}
  </div>
  <a
    href="{% url 'project:upload_file' project.id%}"
    class="py-4 px-8 bg-slate-500 text-white inline-block rounded-full hover:opacity-80 transition"
    >Upload File</a
  >

  <h2 class="mt-6 mb-4 text-2xl font-semibold">Notes:</h2>
  <hr />
  <div class="mt-6 grid grid-cols-4 gap-4">
    {% for note in project.notes.all %}
    <a href="{% url 'project:note' project.id note.id%}">
      <div class="py-6 px-6 bg-neutral-200 rounded-xl mb-6">
        <h3 class="text-xl font-medium">{{note.name}}</h3>
        <p class="mt-2 text-sm text-neutral-500">
          {{note.body |truncatechars:50}}
        </p>
      </div>
    </a>
    {% endfor %}
  </div>
  <a
    href="{% url 'project:add_note' project.id%}"
    class="py-4 px-8 bg-amber-500 text-white inline-block rounded-full hover:opacity-80 transition"
    >Add Note</a
  >
</div>
{% endblock content %}

project/templates/project/projects.html
{% extends "core/base.html" %} 
{% block content %}
<div class="p-4 h-full">
  <h1 class="text-3xl mb-6 font-bold text-center">Projects</h1>
  <hr />
  <a
  href={% url 'project:add_project' %}

    class="mt-4 py-4 px-8 bg-sky-600 text-white inline-block rounded-full hover:opacity-80 transition font-semibold"
    >Add project <span class="ml-[1px] text-lg">+</span></a
  >
  {% if not projects %}
  <p class="italic text-neutral-600 text-center">No projects available.</p>
  {% endif %}
  <div class="mt-6 grid grid-cols-4 gap-4">
    {% for project in projects %}
    <a href="{% url 'project:project' project.id %}">
      <div
        class="py-6 px-6 bg-slate-200 rounded-xl shadow-lg hover:opacity-80 transition"
      >
        <h2 class="text-xl font-bold">{{project.name}}</h2>
        <p class="mt-2 text-sm text-slate-600 font-medium">
          {{project.created_at}}
        </p>
        <p class="mt-2 text-base text-slate-600 font-medium">
          {{project.description}}
        </p>
        <p class="mt-2 text-base text-slate-600 font-medium">
          To-do List: {{project.todolists.all|length}}
        </p>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

project/templates/project/upload_file.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="p-4">
        <h1 class="mb-6 text-3xl font-semibold">Upload file to "{{ project.name }}"</h1>

        <form method="post" action="." enctype="multipart/form-data" class="mt-2 space-y-6">
            {% csrf_token %}

            {{ form.as_p }}

            <div>
                <button class="mt-2 py-4 px-8 bg-sky-600 text-white rounded-full font-bold hover:opacity-80 transition">Upload</button>
            </div>
        </form>
    </div>
{% endblock %}