account/urls.py
from django.urls import path
from . import views
app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dotpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add_project, name='add_project'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit_project, name='edit_project'),
    path('<uuid:pk>/delete/', views.delete_project, name='delete_project'),
    path('<uuid:project_id>/files/upload/',
         views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/',
         views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note, name='note'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/',
         views.edit_note, name='edit_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/',
         views.delete_note, name='delete_note'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    if request.user.is_authenticated:
        return redirect('/projects/')
    
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends "core/base.html" %}
{% block content %}
<h1 class="text-3xl">About</h1>
<div class="mt-6 space-y-6">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, voluptate praesentium facilis iusto porro sunt obcaecati nobis? Eius laudantium autem, voluptate totam aspernatur delectus? Qui labore impedit et minus itaque!
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, voluptate praesentium facilis iusto porro sunt obcaecati nobis? Eius laudantium autem, voluptate totam aspernatur delectus? Qui labore impedit et minus itaque!
    </p>
</div>
{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
  </head>
  
  <body class="flex flex-col min-h-screen h-full">
    <style>
      * {
        font-family: 'Roboto', sans-serif;
      }
    </style>
    <nav class="py-6 px-8 bg-emerald-800 flex  items-center justify-between">
      <h1 class="text-white text-3xl">
        <a href="{% url 'core:index'%}">
        <h1 class="text-3xl font-bold">dotPM</h1>
        </a>
      </h1>
      <div class="space-x-4">
        {% comment %} <a href="{% url 'core:about'%}" class="text-white">About</a> {% endcomment %}
        {% if request.user.is_authenticated%}
        <a href="{% url 'project:projects'%}" class="py-4 px-8 bg-emerald-600 text-white rounded-full hover:opacity-80 font-bold">Projects</a>
        <a href="{% url 'account:logout'%}" class="py-4 px-8 bg-amber-600 text-white rounded-full hover:opacity-80 font-bold">Log Out</a>
        {% else %}
        <a href="{% url 'account:login'%}" class="py-4 px-8 bg-emerald-600 text-white rounded-full hover:opacity-80 font-bold">Log In</a>
        <a href="{% url 'account:signup'%}" class="py-4 px-8 bg-sky-600 text-white rounded-full hover:opacity-80 font-bold">Sign Up</a>
        {% endif %}
        
      </div>
    </nav>
    <main class="py-6 px-8 flex-grow">
      {% block content %}{% endblock content %}
    </main>
    <footer class="py-8 px-8 bg-emerald-800 text-white text-center text-lg">
      <p>Copyright &copy; 2023 - dotpm</p>
    </footer>
  </body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
<div class="min-h-[75vh] flex items-center justify-between p-8">
  {% if not request.user.is_authenticated %}
  <div class="max-w-2xl space-y-4">
    <h1 class="lg:text-3xl text-4xl font-bold text-emerald-700">Streamlining Success, One Task at a Time – Your Ultimate Project Management Solution.</h1>
    <a href="{% url 'account:signup'%}" class=""><h1 class="mt-4 w-fit py-4 px-8 border border-neutral-300 bg-emerald-800 text-white text-lg rounded-xl font-semibold hover:opacity-80">Sign Up</h1></a>
  </div>
  <div class="max-w-2xl w-full  grid-cols-3 gap-6 hidden lg:grid">
    <div class="h-[200px] font-bold text-white text-2xl flex justify-center items-center col-span-2 rounded-xl bg-emerald-600 shadow-xl hover:scale-105 transition">
     
    </div>
    <div class="h-[200px] font-bold text-white text-2xl flex justify-center items-center col-span-1 rounded-xl bg-sky-600 shadow-xl hover:scale-105 transition">
      
    </div>
    <div class="h-[200px] font-bold text-white text-2xl flex justify-center items-center col-span-1 rounded-xl bg-amber-600 shadow-xl hover:scale-105 transition">
      
    </div>
    <div class="h-[200px] font-bold text-white text-2xl flex justify-center items-center col-span-2 rounded-xl bg-slate-600 shadow-xl hover:scale-105 transition">
      
    </div>
    
  </div>
  {% else %}
  
  {% endif %}

</div>
{% endblock content %}